### ISSUE TITLE
Identify and add standard parser-related columns to all tables

### ISSUE THREAD

**Issue by gfr10598** [m-lab/etl#285]
EDIT(soltesz): Ensure that all tables include standard parser columns:

- test_id
- task_filename
- parser_version
- parse_time
- log_time

* [x] - ndt
* [x] - sidestream
* [x] - paris-traceroute
* [x] - disco

**Comment by gfr10598** [comment]
Also need to add task_filename.

**Comment by stephen-soltesz** [comment]
https://github.com/m-lab/etl-schema/tree/master/schema

* ndt legacy.json missing: `parser_version, `parse_time`, `task_filename`
* paris-traceroute missing: `parser_version` `parse_time`, `task_filename`
