### ISSUE TITLE
queue-pusher service should be auto-deployed

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/etl#287]
While investigating failures in queue pusher due failing validation of archive names, we discovered that the version running in production was last deployed in June 2017.

Rather than depending on manual deployments, queue-pusher service should be auto-deployed like the other parts of the ETL pipeline.

**Comment by gfr10598** [comment]
.travis.yml changes in #380 a "prod-*" target, which includes deployment of queue_pusher for prod, and a staging target that auto-deploys to staging on merge to integration.
