### ISSUE TITLE
_PARTITIONTIME missing from production table views 

### ISSUE THREAD

**Issue by mattmathis** [m-lab/etl#391]
This query fails:
#standardSQL
SELECT
  _PARTITIONTIME AS pt,
  COUNT(*) AS count
FROM
  `measurement-lab.internal_v3_1.common_etl`
GROUP BY
  pt
ORDER BY
  pt

This query works:
#standardSQL
SELECT
  _PARTITIONTIME AS pt,
  COUNT(*) AS count
FROM
  `measurement-lab.public.ndt`
GROUP BY
  pt
ORDER BY
  pt

**Comment by gfr10598** [comment]
This is a misunderstanding.  In views, one should use the partition_date psuedo-field.  BQ will then map this onto the _PARTITIONDATE when it compiles the query.
