### ISSUE TITLE
Switch pipeline to write (SS, PT) to base_tables instead of public

### ISSUE THREAD

**Issue by gfr10598** [m-lab/etl#403]
We have agreed to change the dataset for the streaming pipeline to base_tables.
We also need, within a day, to copy all the tables.  So
1.  Populate base_tables/ndt with all of 2017 data.
2.  code, review and commit
3.  suspend task queue
4.  deploy (with new prod tag - NDT only)
5.  Copy past month Jan 2018 from public to base_tables
6.  resume task queue

**Comment by gfr10598** [comment]
NDT pipeline is done.  PT and SS still need to be done.

**Comment by stephen-soltesz** [comment]
The DISCO parser is writing to base_tables in staging. And will when we promote it to prod.

**Comment by stephen-soltesz** [comment]
https://github.com/m-lab/etl/pull/451 updates sidestream & pt to write to base_tables globally.

**Comment by stephen-soltesz** [comment]
TODO: 

* create measurement-lab:base_tables.sidestream 
* create measurement-lab:base_tables.traceroute
* tag production releases for sidestream & PT parsers to production

**Comment by gfr10598** [comment]
This will go to production if we do a "small" prod rollout.  This would be problematic, as someone needs to:
  1. Suspend the task queues
  2. Copy the tables
  3. Rollout the new binary
  4. Re-enable the task queues.

**Comment by pboothe** [comment]
Obsolete
