### ISSUE TITLE
PT tests in BigQuery drop after pollution handling deployment

### ISSUE THREAD

**Issue by yachang** [m-lab/etl#407]
SELECT
  num_tests,
FROM
  (
SELECT 
COUNT(*) num_tests
FROM 
[measurement-lab:public.traceroute]
WHERE
   _PARTITIONTIME >= "2018-01-30 00:00:00" 
   AND _PARTITIONTIME < "2018-01-31 00:00:00" 
)
GROUP BY
  num_tests

For 01/29/2018, daily rows are 46 millions.
After deployment on 01/30/2018, the parsed rows for 01/30/2018 dropped to 15 millions.

**Comment by gfr10598** [comment]
Something caused the cpu utilization to drop, so AE wasn't spinning up more instances, so the throughput dropped.

Probably should start by understanding why the CPU utilization dropped.
https://screenshot.googleplex.com/Ujqkme3PRwC.png

**Comment by yachang** [comment]
The drop is caused by

1. Lower processing speed introduced by pollution check.
2. A bug in pollution check code which caused the crash of workers.

Both of them fixed in https://github.com/m-lab/etl/pull/413

The CPU utilization back to > 80%. The task queue for PT parser drop from 2K+ to 0 now.
