### ISSUE TITLE
sidestream data includes malformed IPv6 addresses

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/etl#465]
The sidestream parser is reporting errors for IPv6 addresses:
```
task.go:125: Invalid server IP address: 2001:4c08:2003:3f:::230 with error: IP not parsable. 
task.go:125: Invalid server IP address: 2001:4c08:2003:3f:::238 with error: IP not parsable.
task.go:125: Invalid server IP address: 2001:438:fffd:2d:::160 with error: IP not parsable.
task.go:125: Invalid server IP address: 2001:438:fffd:2d:::153 with error: IP not parsable.
task.go:125: Invalid server IP address: 2001:1af8:4900:b070:::212 with error: IP not parsable.
```

These prefixes appear to be from the local server address. https://github.com/m-lab/operator/blob/master/plsync/sites.py#L159

So that we are including IPv4 & all IPv6 sidestream metrics, the parser should attempt to correct these malformed IPv6 addresses.

This bug is likely in the web100 kernel itself  and likely to be present in all historical data with ipv6 addresses.

**Comment by mattmathis** [comment]
The kernel only keeps addresses as 32 or 128 bit binary objects.    Sidestream converts them to printable strings.   Several years ago Josh fixed a bug in the original Web100 library, by deleting private IPv6 conversion code and switching the native system library.   (The Web100 library predated standard system library IPv6 support by several years).

**Comment by stephen-soltesz** [comment]
I see these in sandbox when trying to process all sidestream data (including embargo) but we do not see these "Invalid server IP address" errors in the mlab-oti logs..  I don't understand why yet.

**Comment by stephen-soltesz** [comment]
Ah, It appears that IPv6 addrs with three colons are not in the embargo whitelist, so get placed into the embargo archive, where they would be masked until reprocessing.

**Comment by gfr10598** [comment]
The SS parser now handles this, since #467.  The web100 code still produces the error, though.

**Comment by stephen-soltesz** [comment]
The etl-embargo logic now parses the three-colon IPv6 addresses correctly and acts accordingly.

There are open issues to deploy this to production and automate the update of the whitelist files.

https://github.com/m-lab/etl-embargo/issues/11
https://github.com/m-lab/etl-embargo/issues/16
