### ISSUE TITLE
pt_schema.go has annotation errors

### ISSUE THREAD

**Issue by gfr10598** [m-lab/etl#512]
json ignores anything after whitespace in an annotion.

+ go vet ./annotation/... ./appengine/... ./fake/... ./metrics/... ./schema/... ./task/... ./web100/...
# github.com/m-lab/etl/schema
schema/pt_schema.go:9: struct field tag `json:"protocal, string"` not compatible with reflect.StructTag.Get: suspicious space in struct tag value
schema/pt_schema.go:10: struct field tag `json:"src_ip, string"` not compatible with reflect.StructTag.Get: suspicious space in struct tag value
schema/pt_schema.go:11: struct field tag `json:"src_af, int32"` not compatible with reflect.StructTag.Get: suspicious space in struct tag value

**Comment by pboothe** [comment]
Obsolete
