### ISSUE TITLE
Annotate connection.server_geolocation using correct, known values

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/etl#543]
The lat/long annotations for our server IPs are comically out of sync with reality.

We maintain authoritative lat/long values for mlab-ns. The server geolocation lat/long should use the same values as those used by mlab-ns.

```
connection_spec.server_geolocation.latitude
connection_spec.server_geolocation.longitude
```

**Comment by gfr10598** [comment]
Probably would make most sense to keep a server annotation cache on in each instance of the pipeline.  Cache should be loaded from authoritative source on startup, and cache misses should probably just go to the annotation service.

**Comment by critzo** [comment]
I've added the review/triage tag based on a report from CIRA about this inaccuracy. Our server locations are static, so why does the annotator-service even need to be used for the server geo fields?

**Comment by gfr10598** [comment]
Some of this info is in sites.py and site-info repo

**Comment by stephen-soltesz** [comment]
mlab-ns uses the https://storage.googleapis.com/operator-mlab-oti/metadata/v0/current/mlab-site-stats.json this is the canonical output format generated by sites.py and now siteinfo.

**Comment by yachang** [comment]
Expect to work on it Sept. 2019.

**Comment by stephen-soltesz** [comment]
The canonical source or this data is now part of the siteinfo api -- https://siteinfo.mlab-oti.measurementlab.net/v1/sites/locations.json

**Comment by pboothe** [comment]
UUID annotator now does this.

**Comment by pboothe** [comment]
We are still potentially mislabeling old data.

**Comment by pboothe** [comment]
Obsolete in favor of alternate strategy of creating synthetic UUID-annotator data for historical data. #876
