### ISSUE TITLE
Field based partitions

### ISSUE THREAD

**Issue by gfr10598** [m-lab/etl#558]
Currently we are using "ingestion-time" partitioning, which uses the time a row is written, or explicit table decorator, to determine what partition to use.

Bigquery now uses "partitioned tables" to refer to field based partitioning, which associate the partition date with the value of a field in the schema, and automatically places rows into the write partition.  This simplifies code and queries, as it largely eliminates the use of decorators or use of the _PARTITIONTIME pseudo-column.

However, it appears from https://cloud.google.com/bigquery/docs/managing-partitioned-table-data that Legacy SQL cannot be used with field based partitioned tables.  This means that using them in M-Lab would preclude anyone using Legacy SQL on such tables.

**Comment by gfr10598** [comment]
Perhaps we should start using field-based partitioning for tables OTHER THAN NDT.  The new sidestream, DISCO, and PT tables have few or no existing users.  But conversion of NDT over to field-based might be relatively painful in the short term.

If our experience with field-based tables with sidestream (and others) is positive, then we can move forward at a later date with converting NDT.

**Comment by gfr10598** [comment]
We might additionally want to start by only converting sidestream batch to use field-based partitioning.  We can later update the daily pipeline to also use field-based.

**Comment by pboothe** [comment]
DECISION: The things that currently use explicit partitions should keep using explicit partitions for the next ~year. Field-based partitions are the way of the future, so we will move to them in the future, but the switch breaks too many things to be considered in scope for the swarm.
