### ISSUE TITLE
file read/write error on web100.Open

### ISSUE THREAD

**Issue by gfr10598** [m-lab/etl#57]
parser/ndt.go
"file read/write error" (WEB100_ERR_FILE)
on call to web100.Open(tmpFile.Name(), legacyNames)
For example:
2017/05/02 11:48:15 ndt.go:115: legacyNames error: 2016/01/26/20160126T18:34:40.536492000Z_acib7.neoplus.adsl.tpnet.pl:55968.c2s_snaplog, when processing: gs://m-lab-sandbox/ndt/2016/01/26/20160126T000000Z-mlab1-prg01-ndt-0007.tgz
file read/write error

**Comment by stephen-soltesz** [comment]
These errors appear to be legitimately due to corrupted files. I believe the issue is "working as intended."
