### ISSUE TITLE
Annotation request: should reuse the connections instead of making a new one for each request

### ISSUE THREAD

**Issue by yachang** [m-lab/etl#583]
Otherwise, when annotator is trying to loading new dataset, there will be tons of errors like:

server.go:2979: http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s

**Comment by yachang** [comment]
fd leak was from annotator server side. 

https://prometheus.mlab-sandbox.measurementlab.net/graph?g0.range_input=2h&g0.expr=process_open_fds%7Bservice%3D%22annotator%22%7D&g0.tab=0

**Comment by pboothe** [comment]
Obsolete
