### ISSUE TITLE
flaky test blocked travis deployment

### ISSUE THREAD

**Issue by yachang** [m-lab/etl#634]
A new release cannot be deployed because of test failure:

0.00s$ if [[ $EC != 0 ]]; then false; fi ;
The command "if [[ $EC != 0 ]]; then false; fi ;" exited with 1.

**Comment by yachang** [comment]
The command "if [[ -n "$TEST_SERVICE_ACCOUNT_mlab_testing" ]] ; then for module in metrics ; do go test -v -coverpkg=$COVER_PKGS -coverprofile=${module//\//_}.cov github.com/m-lab/etl/$module -tags=integration ; EC=$[ $EC || $? ] ; done ; echo "summary status $EC" ; if [[ $EC != 0 ]]; then false; fi ; fi" exited with 1.

**Comment by yachang** [comment]
https://travis-ci.org/m-lab/etl/builds/512548832

**Comment by pboothe** [comment]
https://github.com/m-lab/etl/pull/635/files

**Comment by yachang** [comment]
https://github.com/m-lab/etl/pull/635 merged and should fix this problem.
