### ISSUE TITLE
high missing annotation rate for PT

### ISSUE THREAD

**Issue by yachang** [m-lab/etl#701]
The following metrics are from sandbox batch:

# TYPE etl_annotation_missing_total counter
etl_annotation_missing_total{type="Empty PT ASN"} 252415
etl_annotation_missing_total{type="Empty PT Geo"} 14386
etl_annotation_missing_total{type="Empty ann.Geo"} 2267
etl_annotation_missing_total{type="Empty ann.Network"} 93
etl_annotation_missing_total{type="Empty ann.Network for PT client IP"} 28675

etl_insertion_time_seconds_bucket{status="succeed",table="scamper",le="0.001"} 0
etl_insertion_time_seconds_bucket{status="succeed",table="scamper",le="0.003"} 0
etl_insertion_time_seconds_bucket{status="succeed",table="scamper",le="0.01"} 0
etl_insertion_time_seconds_bucket{status="succeed",table="scamper",le="0.03"} 0
etl_insertion_time_seconds_bucket{status="succeed",table="scamper",le="0.1"} 1926
etl_insertion_time_seconds_bucket{status="succeed",table="scamper",le="0.2"} 36459
etl_insertion_time_seconds_bucket{status="succeed",table="scamper",le="0.5"} 60799
etl_insertion_time_seconds_bucket{status="succeed",table="scamper",le="1"} 61514
etl_insertion_time_seconds_bucket{status="succeed",table="scamper",le="2"} 61555
etl_insertion_time_seconds_bucket{status="succeed",table="scamper",le="5"} 61556
etl_insertion_time_seconds_bucket{status="succeed",table="scamper",le="10"} 61558
etl_insertion_time_seconds_bucket{status="succeed",table="scamper",le="20"} 61558
etl_insertion_time_seconds_bucket{status="succeed",table="scamper",le="50"} 61558
etl_insertion_time_seconds_bucket{status="succeed",table="scamper",le="100"} 61558
etl_insertion_time_seconds_bucket{status="succeed",table="scamper",le="200"} 61558
etl_insertion_time_seconds_bucket{status="succeed",table="scamper",le="+Inf"} 61558
etl_insertion_time_seconds_sum{status="succeed",table="scamper"} 12443.343155981005
etl_insertion_time_seconds_count{status="succeed",table="scamper"} 61558

**Comment by yachang** [comment]
"Empty PT ASN" & "Empty PT Geo" are counted per hop
Which mean that the % of missing hop Geo & ASN annotation is very high.

"Empty ann.Network for PT client IP" are for client IP per test, which is high too. I will continue to update this thread for more info.

**Comment by yachang** [comment]
Here is some BQ results:

#standardSQL
SELECT
  COUNTIF(s_latitude IS NOT NULL AND s_longitude IS NOT NULL) AS value_source_geo_success,
  COUNTIF(d_latitude IS NOT NULL AND d_longitude IS NOT NULL) AS value_dest_geo_success,
  COUNT(*) AS value_total

FROM (
  SELECT
    Source.geo.latitude as s_latitude,
    Source.geo.longitude as s_longitude,
    Destination.geo.latitude as d_latitude,
    Destination.geo.longitude as d_longitude

  FROM
    `mlab-sandbox.batch.scamper_20160724`


  GROUP BY
    TestTime,
    Source.geo.latitude,
    Source.geo.longitude,
    Destination.geo.latitude,
    Destination.geo.longitude
)


Row	value_source_geo_success	value_dest_geo_success	value_total	
1	
89929
65675
91695

**Comment by gfr10598** [comment]
I think the low geo annotation rate for hops is to be expected.  I expect MaxMind doesn't work very hard to find geo annotations for internal routers.

I'm a bit more surprised that the ASN annotations are even worse.  Might be worth discussing with CAIDA and maybe with IPInfo to understand this better.  Is there a pattern to the IPs for hops that are missing ASN data?

**Comment by pboothe** [comment]
https://github.com/m-lab/dev-tracker/issues/293
