### ISSUE TITLE
deployment to staging failed.

### ISSUE THREAD

**Issue by gfr10598** [m-lab/etl#713]
Activated service account credentials for: [etl-travis-deploy@mlab-staging.iam.gserviceaccount.com]
Configurations to update:
descriptor:      [/home/travis/gopath/src/github.com/m-lab/etl/appengine/queue.yaml]
type:            [task queues]
target project:  [mlab-staging]
ERROR: (gcloud.app.deploy) PERMISSION_DENIED: Service Usage API has not been used in project 240028626237 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/serviceusage.googleapis.com/overview?project=240028626237 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
- '@type': type.googleapis.com/google.rpc.Help
  links:
  - description: Google developers console API activation
    url: https://console.developers.google.com/apis/api/serviceusage.googleapis.com/overview?project=240028626237
Script failed with status 1
failed to deploy

**Comment by gfr10598** [comment]
Followed the directions: Enable it by visiting https://console.developers.google.com/apis/api/serviceusage.googleapis.com/overview?project=240028626237 then retry.

Not clear why this changed, but seems to be working after enabling this API.

**Comment by pboothe** [comment]
Fixed, but saved here because it will likely bite us for every cloud project.
