### ISSUE TITLE
create cloud function that will fetch tests generated by new platform into daily pipeline

### ISSUE THREAD

**Issue by yachang** [m-lab/etl#734]

**Comment by yachang** [comment]
Currently Gardener takes care of NDT5 data from pusher-{project_name} bucket.

We would like all tests (including new Scamper JSON outputs from pusher-* bucket) processed by daily pipeline as well as Gardener.

**Comment by gfr10598** [comment]
Not clear whether we should set up any new daily pipelines.  Should  definitely set up the copy to archive bucket, and gardener should use archive bucket.
