### ISSUE TITLE
Traceroute parser is failing test count sanity check on dates from June through October.

### ISSUE THREAD

**Issue by gfr10598** [m-lab/etl#749]
https://console.cloud.google.com/datastore/entities;kind=task;ns=gardener/query/kind?cloudshell=true&project=mlab-oti

**Comment by yachang** [comment]
https://github.com/m-lab/etl-gardener/blob/2c3433d693fe50a0a3eda5d030d2f703c5719aff/rex/rex.go#L429

The bar for "Too few tests" error is 99%. Once error triggered, the new parsing results will not be written to BQ table.

**Comment by yachang** [comment]
https://pantheon.corp.google.com/datastore/entities;kind=task;ns=gardener/query/kind;filter=%5B%2210%2FExperiment%7CSTR%7CEQ%7C14%2Fndt%2Ftraceroute%22%5D?cloudshell=true&project=mlab-oti

This error "Too few tests" happened from late June to present this year.

**Comment by yachang** [comment]
Fixed by https://github.com/m-lab/etl/pull/762

**Comment by yachang** [comment]
https://github.com/m-lab/etl/releases/tag/prod-v2.1.1
