### ISSUE TITLE
travis failed to deploy ETL

### ISSUE THREAD

**Issue by yachang** [m-lab/etl#751]
gcloud app deploy --promote app.yaml
INFO: Executing staging command: [/home/travis/google-cloud-sdk/platform/google_appengine/go-app-stager /home/travis/gopath/src/github.com/m-lab/etl/appengine/queue_pusher/app.yaml /home/travis/gopath/src/github.com/m-lab/etl/appengine/queue_pusher /tmp/tmpYm9lU4/tmpuZIwFz]
INFO: ------------------------------------ STDOUT ------------------------------------
------------------------------------ STDERR ------------------------------------
2019/10/29 16:52:05 invalid runtime value go
--------------------------------------------------------------------------------
ERROR: (gcloud.app.deploy) Staging command [/home/travis/google-cloud-sdk/platform/google_appengine/go-app-stager /home/travis/gopath/src/github.com/m-lab/etl/appengine/queue_pusher/app.yaml /home/travis/gopath/src/github.com/m-lab/etl/appengine/queue_pusher /tmp/tmpYm9lU4/tmpuZIwFz] failed with return code [1].
------------------------------------ STDOUT ------------------------------------
------------------------------------ STDERR ------------------------------------
2019/10/29 16:52:05 invalid runtime value go
--------------------------------------------------------------------------------
Script failed with status 1
failed to deploy

**Comment by yachang** [comment]
I tried to update app.yaml for queue_pusher as following:

==============================================
runtime: go111
service: queue-pusher

handlers:
- url: /.*
  script: auto

env_variables:
  # These should be substituted in the travis deployment script.
  RELEASE_TAG: ${TRAVIS_TAG}
  COMMIT_HASH: ${TRAVIS_COMMIT}

======================================================

Which has build error on travis. 

set runtime as custom might be possible alternative solution.

**Comment by yachang** [comment]
Update to go112

same build error:

=========================================

ERROR: (gcloud.app.deploy) Error Response: [9] Cloud build b8014dfa-3f3f-4168-bfd5-02391370b9cd status: FAILURE.
Error ID: 634A9EEF.
Error type: BuildError.
Error message: 2019/10/30 16:29:10 Building /tmp/staging/srv, with main package at ., saving to /tmp/staging/usr/local/bin/start
2019/10/30 16:29:10 Running &{/usr/local/go/bin/go [go build -o /tmp/staging/usr/local/bin/start .] [PATH=/go/bin:/usr/local/go/bin:/builder/google-cloud-sdk/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOSTNAME=246bd95f6742 BUILDER_OUTPUT=/builder/outputs HOME=/builder/home DEBIAN_FRONTEND=noninteractive GOROOT=/usr/local/go/ GOPATH=/go GO111MODULE=on GOCACHE=/tmp/cache GOPATH=/go] /tmp/staging/srv <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> <nil> false [] [] [] [] <nil> <nil>}
2019/10/30 16:29:27 Wrote build output to /builder/outputs/output
2019/10/30 16:29:27 Failed to build app: [go build -o /tmp/staging/usr/local/bin/start .] with env [PATH=/go/bin:/usr/local/go/bin:/builder/google-cloud-sdk/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOSTNAME=246bd95f6742 BUILDER_OUTPUT=/builder/outputs HOME=/builder/home DEBIAN_FRONTEND=noninteractive GOROOT=/usr/local/go/ GOPATH=/go GO111MODULE=on GOCACHE=/tmp/cache GOPATH=/go] failed: err=exit status 1, out="go: finding google.golang.org/appengine v1.6.5\ngo: finding github.com/golang/protobuf v1.3.1\ngo: finding golang.org/x/text v0.3.2\ngo: finding golang.org/x/net v0.0.0-20190603091049-60506f45cf65\ngo: finding golang.org/x/tools v0.0.0-20180917221912-90fa682c2a6e\ngo: finding golang.org/x/text v0.3.0\ngo: finding golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a\ngo: finding golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2\ngo: downloading google.golang.org/appengine v1.6.5\ngo: finding github.com/m-lab/etl/etl latest\ngo: extracting google.golang.org/appengine v1.6.5\ngo: downloading golang.org/x/net v0.0.0-20190603091049-60506f45cf65\ngo: downloading github.com/golang/protobuf v1.3.1\ngo: extracting github.com/golang/protobuf v1.3.1\ngo: finding github.com/m-lab/etl v0.7.2\ngo: downloading github.com/m-lab/etl v0.7.2\ngo: extracting golang.org/x/net v0.0.0-20190603091049-60506f45cf65\ngo: extracting github.com/m-lab/etl v0.7.2\n-> unzip /go/pkg/mod/cache/download/github.com/m-lab/etl/@v/v0.7.2.zip: malformed file path \"parser/testdata/20160112T00:45:44Z_ALL27409.paris\": invalid char ':'\nbuild github.com/m-lab/etl/appengine/main: cannot load github.com/m-lab/etl/etl: cannot find module providing package github.com/m-lab/etl/etl\n".
Script failed with status 1

**Comment by yachang** [comment]
Date about deprecation of go1.9 support:

https://cloud.google.com/appengine/docs/deprecations/

officially deprecated from 10/01/2019.

shutdown date TBD now

**Comment by pboothe** [comment]
uUrrently blocked on ETL simplification work

**Comment by gfr10598** [comment]
If this starts failing in prod, we may need to re-implement with new flex library and delete the queue_pusher.

**Comment by pboothe** [comment]
We have removed the queue_pusher deployment from travis. Closing this issue as complete. This raised the priority of ETL cleanup work.
