### ISSUE TITLE
Traceroute BQ table schema change

### ISSUE THREAD

**Issue by yachang** [m-lab/etl#757]
delete old tables and create new ones with new schema defined in 

https://github.com/m-lab/etl/pull/750

There are 2 new top level fields:

ExpVersion     string       `json:"traceroute_caller_version,string" bigquery:"exp_version"`

	CachedResult   bool         `json:"cached_result,bool" bigquery:"cached_result"`

**Comment by gfr10598** [comment]
This does not require delete/create.  The update-schema command will handle this.

**Comment by yachang** [comment]
Fixed by #750
