### ISSUE TITLE
ETL deployment blocked by migrating from legacy to split health checks

### ISSUE THREAD

**Issue by yachang** [m-lab/etl#758]
https://cloud.google.com/appengine/docs/flexible/java/migrating-to-split-health-checks

ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: Legacy health checks are no longer supported for the App Engine Flexible environment. This app's feature setting is configured to use legacy health checks by default. For instructions on migrating to split health checks see https://cloud.google.com/appengine/docs/flexible/java/migrating-to-split-health-checks
Script failed with status 1

**Comment by yachang** [comment]
Fixed by running

gcloud app update --split-health-checks --project mlab-sandbox

gcloud app update --split-health-checks --project mlab-staging

gcloud app update --split-health-checks --project mlab-oti

**Comment by mehtab11** [comment]
Closing this issue.
