### ISSUE TITLE
tcp-info batch jobs are not completing

### ISSUE THREAD

**Issue by gfr10598** [m-lab/etl#792]
We discovered that since mid-November, data from some machines on lax04 and sea04 are not being processed.  This week, this problem has expanded to most tcpinfo daily data, likely due to the successful deployment of traceroute fixes, which have increased the load on the batch processors.

Currently, many tcpinfo reprocessing jobs and daily jobs are failing to complete within the 12 hour task queue limit, so no data is being written for those task files.

However, since this started on just a few machines, it seems to be a characteristic of the task processing, not the full queue draining.  It is likely therefore that the parser is failing to complete the parsing of individual tar files within the appengine timeout, and these files are being retried over and over.

**Comment by gfr10598** [comment]
After increasing number of CPUs, the most recent days seem to have reprocessed successfully.  However, there are still 4 machines that are missing large numbers of tcpinfo records:

row | count|  bad  |       date      | site
133 | 5424 | 0.714 | 2020-01-08 | sea04 |  
134 | 12396 | 0.685 | 2020-01-08 | lax04 |  
135 | 6872 | 0.675 | 2020-01-08 | den02 |  
136 | 8684 | 0.651 | 2020-01-08 | mia06 |  

137 | 10302 | 0.694 | 2020-01-07 | mia06 |  
138 | 6907 | 0.67 | 2020-01-07 | den02 |  
139 | 14328 | 0.658 | 2020-01-07 | lax04 |  
140 | 5905 | 0.652 | 2020-01-07 | sea04

**Comment by gfr10598** [comment]
Better view of the problem:
https://console.cloud.google.com/bigquery?sq=515150309683:05faa49826084d55962d39edd34d9478

Row | site_total | site | date | mlab1 | mlab2 | mlab3 | mlab4 |  
-- | -- | -- | -- | -- | -- | -- | -- | --
1 | 21992 | den02 | 2020-01-08 00:00:00 UTC | 21992 | 0 | 0 | 0 |  
2 | 67018 | iad03 | 2020-01-08 00:00:00 UTC | 31102 | 0 | 35916 | 0 |  
3 | 22357 | lax04 | 2020-01-08 00:00:00 UTC | 22357 | 0 | 0 | 0 |  
4 | 22146 | mia06 | 2020-01-08 00:00:00 UTC | 22146 | 0 | 0 | 0 |  
5 | 92793 | ord04 | 2020-01-08 00:00:00 UTC | 0 | 50286 | 42507 | 0 |  
6 | 14510 | sea04 | 2020-01-08 00:00:00 UTC | 14509 | 0 | 1 | 0 |  
7 | 21607 | den02 | 2020-01-07 00:00:00 UTC | 21607 | 0 | 0 | 0 |  
8 | 66346 | iad03 | 2020-01-07 00:00:00 UTC | 29858 | 0 | 36488 | 0 |  
9 | 24074 | lax04 | 2020-01-07 00:00:00 UTC | 24055 | 19 | 0 | 0 |  
10 | 23363 | mia06 | 2020-01-07 00:00:00 UTC | 23363 | 0 | 0 | 0 |  
11 | 103740 | ord04 | 2020-01-07 00:00:00 UTC | 0 | 47494 | 56246 | 0 |  
12 | 18211 | sea04 | 2020-01-07 00:00:00 UTC | 18211 | 0 | 0 | 0

**Comment by gfr10598** [comment]
Looks like there are actually no archives for these machines.  There are archives for ndt5, but not for tcpinfo.  So this is actually a platform issue!!!

**Comment by gfr10598** [comment]
iad03 has no data coming in from mlab2 for either ndt5 or tcpinfo.  May be related or something different.

**Comment by stephen-soltesz** [comment]
Was this resolved by the pusher/TSO fix?

**Comment by mehtab11** [comment]
Fixed; closing it.
