### ISSUE TITLE
sandbox deployment blocked by missing data-processing cluster

### ISSUE THREAD

**Issue by yachang** [m-lab/etl#809]
ERROR: (gcloud.container.clusters.get-credentials) ResponseError: code=404, message=Not found: projects/mlab-sandbox/zones/us-east1-b/clusters/data-processing

Could not find [data-processing] in [us-east1-b].
Did you mean [data-processing] in [us-east1]?
Script failed with status 1

**Comment by yachang** [comment]
https://pantheon.corp.google.com/kubernetes/list?organizationId=433637338589&project=mlab-sandbox

There is data processing cluster:

Name	Location	Cluster size	Total cores	Total memory	Notifications	Labels			
 data-processing	us-east1	21	192 vCPUs	720.00 GB	
 Low resource requests
data-processing : true		
 data-processing-cluster	us-central1-a	11	40 vCPUs	138.60 GB	
 Low resource requests
data-processing : true		
 prometheus-federation	us-central1-c	8	59 vCPUs	331.25 GB	
 soltesz-testing	us-east1-d	3	6 vCPUs	22.50 GB	
 Low resource requests
 viz-cluster	us-central1-a	3	24 vCPUs	90.00 GB	
 Low resource requests

**Comment by yachang** [comment]
https://travis-ci.org/m-lab/etl/builds/644381152

**Comment by stephen-soltesz** [comment]
The travis submodule is out of date in the sandbox-emptyr branch. Please try updating it with something like:

    git submodule update --init --recursive
