### ISSUE TITLE
Stop generating empty rows from traceroute code path

### ISSUE THREAD

**Issue by yachang** [m-lab/etl#817]
SELECT
ParseInfo.ParseTime AS parse_time,
Parseinfo.TaskFileName AS task_filename
FROM `mlab-oti.ndt.traceroute`
GROUP BY parse_time, task_filename
ORDER BY parse_time ASC
LIMIT 1000

Row | parse_time | task_filename |  
-- | -- | -- | --
1 | 0001-01-01 00:00:00 UTC |   |  
2 | 2019-08-19 05:34:32.009017 UTC | gs://archive-measurement-lab/paris-traceroute/2013/05/24/20130524T000000Z-mlab3-akl01-paris-traceroute-0000.tgz |  
3 | 2019-08-19 05:34:32.009183 UTC | gs://archive-measurement-lab/paris-traceroute/2013/05/24/20130524T000000Z-mlab3-akl01-paris-traceroute-0000.tgz |  
4 | 2019-08-19 05:34:32.009356 UTC | gs://archive-measurement-lab/paris-traceroute/2013/05/24/20130524T000000Z-mlab3-akl01-paris-traceroute-0000.tgz

**Comment by yachang** [comment]
There is no such empty rows with the latest deployment.

**Comment by mehtab11** [comment]
Closed.
