### ISSUE TITLE
Figure out reason why some legacy PT tests cannot be reprocessed after 2019/08/19

### ISSUE THREAD

**Issue by yachang** [m-lab/etl#818]
1 | 2019-08-19 05:34:32.009017 UTC | gs://archive-measurement-lab/paris-traceroute/2013/05/24/20130524T000000Z-mlab3-akl01-paris-traceroute-0000.tgz |  
-- | -- | -- | --
2 | 2019-08-19 05:34:32.009183 UTC | gs://archive-measurement-lab/paris-traceroute/2013/05/24/20130524T000000Z-mlab3-akl01-paris-traceroute-0000.tgz |  
3 | 2019-08-19 05:34:32.009356 UTC | gs://archive-measurement-lab/paris-traceroute/2013/05/24/20130524T000000Z-mlab3-akl01-paris-traceroute-0000.tgz |  
4 | 2019-08-19 05:34:32.009531 UTC | gs://archive-measurement-lab/paris-traceroute/2013/05/24/20130524T000000Z-mlab3-akl01-paris-traceroute-0000.tgz |  

The tests in that tarball looks normal:

SELECT
*
FROM `mlab-oti.ndt.traceroute`
WHERE Parseinfo.TaskFileName = "gs://archive-measurement-lab/paris-traceroute/2013/05/24/20130524T000000Z-mlab3-akl01-paris-traceroute-0000.tgz"
LIMIT 1000

**Comment by yachang** [comment]
Look into mlab-oti, batch dataset, traceroute_yyyymmdd, and there are 3 single day table in 2013:

![Screenshot from 2020-02-20 11-02-27](https://user-images.githubusercontent.com/8365769/74954063-85b8b880-53d0-11ea-93b7-21c09805cdbd.png)


Since 2019/09/09, it kept dup itself (should be < 100M for a single day data, but now > 15G), but cannot be copied into partitioned table.

I will manually delete this daily table to give it a second chance.

**Comment by yachang** [comment]
After I deleted the traceroute_20130524 daily table manually,

For mlab-staging:
 it was recreated, and stay there, not be deleted. BUT, the partitioned table got refreshed data:

SELECT 
ParseInfo.ParseTime AS parse_time,
Parseinfo.TaskFileName AS task_filename
FROM `mlab-staging.batch.traceroute`
WHERE _PARTITIONTIME = "2013-05-24"
GROUP BY parse_time, task_filename
ORDER BY parse_time ASC

Here is output:

Row	parse_time	task_filename	
1	
2020-02-20 15:05:55.072172 UTC
gs://archive-measurement-lab/paris-traceroute/2013/05/24/20130524T000000Z-mlab3-arn01-paris-traceroute-0000.tgz
2	
2020-02-20 15:05:55.148962 UTC
gs://archive-measurement-lab/paris-traceroute/2013/05/24/20130524T000000Z-mlab3-ham01-paris-traceroute-0000.tgz
3	
2020-02-20 15:05:55.150866 UTC
gs://archive-measurement-lab/paris-traceroute/2013/05/24/20130524T000000Z-mlab3-ham01-paris-traceroute-0000.tgz
4	
2020-02-20 15:05:55.150939 UTC
gs://archive-measurement-lab/paris-traceroute/2013/05/24/20130524T000000Z-mlab3-ham01-paris-traceroute-0000.tgz

**Comment by yachang** [comment]
The same thing happened to mlab-oti, partitioned table got updated, but the daily table not deleted because the sanity check failed at the end of dedup stage:

Task State
{gs://archive-measurement-lab/paris-traceroute/2013/05/24/: Finishing, Mon22:36:57.7, Q:, J:, E:Too few tests (rex.finish)}

So the batch:traceroute table cannot be copied to base_tables

**Comment by yachang** [comment]
Further dig out: there were 21 tarball in previous processing, only 19 now:
WITH old_tar AS 

(SELECT 

DISTINCT(Parseinfo.TaskFileName) AS file,

FROM `mlab-staging.base_tables.traceroute`
WHERE _PARTITIONTIME = "2013-05-24"

),

new_tar AS 
(SELECT 

DISTINCT(Parseinfo.TaskFileName) AS file,
FROM `mlab-staging.batch.traceroute`

WHERE _PARTITIONTIME = "2013-05-24"

)

SELECT * FROM old_tar
  EXCEPT DISTINCT
SELECT * from new_tar

============================


Row | file |  
-- | -- | --
1 | gs://archive-measurement-lab/paris-traceroute/2013/05/24/20130524T000000Z-mlab3-dub01-paris-traceroute-0000.tgz |  
2 | gs://archive-measurement-lab/paris-traceroute/2013/05/24/20130524T000000Z-mlab3-lju01-paris-traceroute-0000.tgz

**Comment by yachang** [comment]
PR: https://github.com/m-lab/etl/pull/830 && https://github.com/m-lab/etl-gardener/pull/232

And https://github.com/m-lab/etl/releases/tag/prod-v2.2.3

Fix this probelm.

In staging, 

SELECT
Parseinfo.ParseTime,
Parseinfo.TaskFileName
FROM `mlab-staging.base_tables.traceroute`
WHERE  _PARTITIONTIME="2013-05-24"
LIMIT 1000

And the output is:





1 | 2020-02-27 16:05:26.383223 UTC | gs://archive-measurement-lab/paris-traceroute/2013/05/24/20130524T000000Z-mlab3-hnd01-paris-traceroute-0000.tgz |  
2 | 2020-02-27 16:05:26.348686 UTC | gs://archive-measurement-lab/paris-traceroute/2013/05/24/20130524T000000Z-mlab3-arn01-paris-traceroute-0000.tgz

**Comment by mehtab11** [comment]
closed.
