### ISSUE TITLE
etl/parser/pt_test.go: TestParseJsonComplex uses invalid JSON

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/etl#824]
The JSON was added in https://github.com/m-lab/etl/pull/730

Today the JSON is reported as invalid. It's possible that later versions of Go are more strict.

To find the invalid portion search for `}],]}]}` -- the extra comma is technically invalid.

See end of line: https://github.com/m-lab/etl/pull/730/files#diff-ec80d12a45783d29c07d2898dc6c6a9fR63

@yachang are there actual scamper results with that extra comma? If so, the parser with later versions of Go may need to take special care to "fix" those results before attempting the JSON parsing.

**Comment by stephen-soltesz** [comment]
Nevermind -- this looks like old news -- I didn't look closely at the code or comments. The failure on my workstation was due to an older version of jsonnet. Carry on.

**Comment by yachang** [comment]
@stephen-soltesz 
Can you close this one? Thanks!
