### ISSUE TITLE
No new ndt5 data since Feb 11

### ISSUE THREAD

**Issue by gfr10598** [m-lab/etl#827]
pboothe reported that the production ndt5 table is out of date.
Discovered that etl batch parser logs show high insert error rate, and no successful rows for ndt5 tasks.

**Comment by gfr10598** [comment]
Possible that the change to ParseInfo struct, in #811, causes failures when the Filename is missing from NDT5.  At the same time, the tcpinfo and traceroute schema were updated by enabling update-schema in travis.

ndt5 update was disabled, because there have been breaking changes in the ndt7 schema, so the update fails.

In the short term, might need to manually update the schema, using "bq update" command.

**Comment by gfr10598** [comment]
To add the Filename field:
```bash
bq --format=prettyjson show mlab-sandbox:batch.ndt5
```

Edit the file to remove header and footer, so file starts with [ and ends with ], with all fields between.
Add the Filename field at the end of the ParseInfo record.

```bash
bq update mlab-sandbox:batch.ndt5 ndt5.json
bq update mlab-sandbox:base_tables.ndt5 ndt5.json
```

**Comment by gfr10598** [comment]
Did same update to staging.  However, only waited about 1 minute after enabling the queues, so may not see any failures.  Batch update effective at 18:57:56 PM

There were just a small number of failures mixed in with successes, starting at 18:57:35pm Eastern.
The last failure was at 19:02:36PM.

The first successful file (zero failures) was at 18:58:08.000 EST, just 12 seconds after the table update.

**Comment by gfr10598** [comment]
Applying to mlab-oti.
Batch table update effective at 7:13:41 PM
First 0 fail file at 19:13:46 EST.
Last complete failure at 19:18:21.000 EST, with only a handful in the previous 60 seconds.

**Comment by gfr10598** [comment]
Paused the task queues in sandbox and staging, so they don't interfere with k8s gardener development.

**Comment by mehtab11** [comment]
Fixed.
