### ISSUE TITLE
Some small tarball not pushed to BQ table due to too big buffer size 

### ISSUE THREAD

**Issue by yachang** [m-lab/etl#829]
this is the root reason of https://github.com/m-lab/etl/issues/818

some early tarball like 

gs://archive-measurement-lab/paris-traceroute/2013/05/24/20130524T000000Z-mlab3-lju01-paris-traceroute-0000.tgz

Only have <10 tests, which is fewer than the buffer size for BQ push, and there is a code bug that omit those pending rows silently.

**Comment by yachang** [comment]
PR: #830 && m-lab/etl-gardener#232

And https://github.com/m-lab/etl/releases/tag/prod-v2.2.3

Fix this problem.

**Comment by mehtab11** [comment]
Fixed; closing it.
