### ISSUE TITLE
Traceroute mise bugs

### ISSUE THREAD

**Issue by yachang** [m-lab/etl#967]
1. Update k8s-support with latest traceroute-caller version.
2. Extra quota with ".json" format, need to be fixed with pt parser unittest
3. Verify that sandbox has ".json" output and correctly parsed in BQ table.

**Comment by stephen-soltesz** [comment]
Please consider updating the datatype name to "traceroute3" now. This will inevitably make the "multi-datatype traceroute" effort simpler. See also: https://docs.google.com/document/d/10LIpwcyk54Qsr6QLMtTvaS818BQP1FjLKoScuGf1_Vw/edit

**Comment by laiyi-ohlsen** [comment]
Obsolete, please refer to Traceroute 3 milestone doc: https://docs.google.com/document/d/1uKTyjtLhCd_A4R0wZQ-bTUNCTkWk19CMq-XeNppmBsg/edit
