### ISSUE TITLE
K8S parser failing file writes in staging

### ISSUE THREAD

**Issue by gfr10598** [m-lab/etl#983]
Probably due to changing node-pools when CPUs changed from 7 to 15.

**Comment by gfr10598** [comment]
Extracted create-parser-pool.sh and updated to correct the storage-rw scope.
Located in etl-gardener/cluster-setup-script branch https://github.com/m-lab/etl-gardener/tree/cluster-setup-script

**Comment by gfr10598** [comment]
Used script to update parser-pool.  Set parser-pool1 size to zero.  Pods migrated and working now.

**Comment by gfr10598** [comment]
TODO:  This type of error should show up in the gardener pipeline overview dashboard.

**Comment by laiyi-ohlsen** [comment]
@gfr10598 Can you make a new issue for the remaining to do?

**Comment by gfr10598** [comment]
The Pipeline Overview prototype dashboard not includes these write failure metrics.

https://grafana.mlab-sandbox.measurementlab.net/d/tDpMHylGk/pipeline-overview?orgId=1&refresh=5m&var-project=mlab-sandbox&var-interval=10m&var-PrometheusDS=Prometheus%20(mlab-sandbox)&var-LegacyDS=Data%20Proc%20(mlab-sandbox)&var-Gardener2_DS=Data%20Processing%20(mlab-sandbox)&var-states=Done&var-states=Processing
